version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_WEBHOOK_URL=https://n8n.spositech.com.br/webhook/creator-prompt
    ports:
      - "80:80"
    restart: unless-stopped
    container_name: spositech-creator-app
    environment:
      - VITE_WEBHOOK_URL=https://n8n.spositech.com.br/webhook/creator-prompt
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_WEBHOOK_URL=https://n8n.spositech.com.br/webhook/creator-prompt
    ports:
      - "8082:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VITE_WEBHOOK_URL=https://n8n.spositech.com.br/webhook/creator-prompt 